paypal/paypal-js

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .nodeops
- README.md
This PR replaces CDNX with [UNPKG](https://unpkg.com/) as our CDN solution.
- UNPKG is a CDN for the public npm registry. With this design, we get CDN functionality for free since we already publish paypal-js to the public registry. We don't have to write any bash code to publish to the CDN like we would need to with cdnx.
- We get versioned urls!
- It seems stable and safe to recommend. Microsoft is using it as their recommended CDN for their new component library: https://www.fast.design/docs/components/getting-started#from-cdn
> Document CDN Usage

- src/main.js
- src/main.test.js
- src/utils.js
- src/utils.test.js
This PR fixes a bug with the error handling with `loadScript()`. It makes sure to clear the `loadingState` variable when an error happens to prevent `loadScript()` from getting into a bad state.
> Ensure that loading errors reset loading state

- e2e-tests/bundle/bundle-size.test.js
- src/main.js
- src/utils.js
- src/utils.test.js
This PR updates the cache logic for the reload use case. This change ensures that both query params and data attributes are validated for the reload use case. 
- If the query params or data attributes change, it will reload the script. 
- If both are the same, it will avoid reloading the script and will return the existing `window.paypal` reference.
> Update cache logic to check data attributes

- scripts/publish.js
Updates the`publish.js` script to use a callback to pass in the OTP flag with `npm publish`.
Attempting to run `npm publish` with the `exec` command from `shelljs` with 2FA enabled exits before allowing the user to enter an OTP.
> Update publish script

- .eslintrc.json
- README.md
- babel.config.js
- e2e-tests/bundle/bundle-size.test.js
- package-lock.json
- package.json
- rollup.config.js
- src/index.js
- src/legacy/index.js
- src/loadScript.js
- src/loadScript.node.test.js
- src/loadScript.test.js
Currently paypal-js includes a promise-polyfill. This polyfill doubles the size of the library. More than 95% of users have browsers that support Promises (source: https://caniuse.com/promises) These users shouldn't have to pay a performance penalty when this polyfill when it's not needed. 
Don't ship with a Promise Polyfill. Instead let's provide a way for users to bring their own Promise implementation to support legacy browsers like IE 11. This change makes the paypal-js over 50% smaller.
See the readme changes for more details.
> Bring your own Promise Polyfill

- .eslintignore
- .eslintrc.json
- babel.config.js
- package-lock.json
- package.json
- rollup.config.js
- src/index.ts
- src/legacy/index.js
- src/legacy/index.ts
- src/load-script.node.test.ts
- src/load-script.test.ts
- src/load-script.ts
- src/utils.test.ts
- src/utils.ts
- tsconfig.json
- types/apis/orders.d.ts
- types/components/buttons.d.ts
- types/index.d.test.ts
- types/index.d.ts
- types/script-options.d.ts
This PR does two things:
- Upgrades the library to use TypeScript
- Exports type declarations for both paypal-js and the `window.paypal` namespace
This branch is currently published to npm using the beta tag. Install it using the following command:
`npm install @paypal/paypal-js@beta`
Here are some screenshots of my editor to show the new helpful auto-suggestions TypeScript devs will get:
Types for `loadScript()`:
Types for `window.paypal`:
Types for `window.paypal` reference returned from loadScript Promise:
There is a high demand for TypeScript types for the JS SDK. For example, the checkout.js library is typed on DefinitelyTyped and gets about 13K downloads a week (https://www.npmjs.com/package/@types/paypal-checkout-components). Let's host the JS SDK types in this repo and be the …
> Use TypeScript and also manage type declarations for the JS SDK

- types/script-options.d.ts
This PR adds `enable-funding` to the valid script options types
> Add enable-funding to script options

- src/load-script.test.ts
- src/load-script.ts
- src/utils.ts
- types/index.d.test.ts
- types/script-options.d.ts
This PR adds support for using custom namespaces. Ex:
```js
// we default to `window.paypal` when no data-namespace is defined.
loadScript({ "client-id": "test", "data-namespace": "customName" })
.then((customObject) => {
customObject.Buttons();
})
```
> Add support for data-namespace option

- README.md
- babel.config.js
- e2e-tests/bundle/bundle-size.test.js
- src/index.ts
- src/legacy/index.ts
- src/load-script.node.test.ts
- src/load-script.test.ts
- src/load-script.ts
- src/utils.test.ts
- src/utils.ts
- types/index.d.test.ts
- types/script-options.d.ts
This PR makes it easier to pass merchant-id values. Now you can pass an array of merchant ids and `loadScript` takes care of setting merchant-id and data-merchant-id to the correct values.
Usage
```js
// multipl merchant-id values
loadScript({ "client-id": "test", "merchant-id": ["123", "456", "789"] });
// <script src="https://www.paypal.com/sdk/js?client-id=test&merchant-id=*" data-merchant-id="123,456,789"></script>
// single merchant-id value
loadScript({ "client-id": "test", "merchant-id": ["123"] });
// <script src="https://www.paypal.com/sdk/js?client-id=test&merchant-id=123"></script>
```
> Add option for passing merchant-id values as an array

- e2e-tests/load-cached-script/index.html
- e2e-tests/load-cached-script/index.test.js
- e2e-tests/reload-script/index.html
- src/utils.test.ts
- src/utils.ts
The `loadScript()` function is designed to prevent unnecessary fetching of the JS SDK script if it's already been loaded with the exact params and data attributes. This logic was also picking up the data-uid-auto attribute which would prevent the matching logic from returning true. This PR fixes the issue by removing this attribute. It also adds tests to cover this use case.
> fix: ignore data-uid-auto attribute in findScript

- types/apis/orders.d.ts
Hi,
I believe that all OrderApplicationContext fields should be optional. This object is optional and its fields should be also not required (https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context)
If it's not then we can't create a PayPal order with for example just this option configured: shipping_preference: 'NO_SHIPPING',
```
const createOrder = (data: UnknownObject, actions: CreateOrderActions) => {
return actions.order
.create({
intent: 'CAPTURE',
application_context: {                                         // here will be error that's additional fields needs to be given
shipping_preference: 'NO_SHIPPING',
},
purchase_units: [
{
description: purchaseDescription,
amount: {
value: price,
currency_code: currencyCode,
},
},
],
})
.then((orderID: string) …
```
> OrderApplicationContext fields should be optional

- types/components/hosted-fields.d.ts
- types/index.d.test.ts
- types/index.d.ts
This PR adds some basic types for the hosted fields component. It builds off of #66. 
Types for `fields`, `styles`, and `cardFields` props are currently typed as unknown objects so there's still work to do here. This PR does enable hosted-fields to work without throwing type errors.
> Types for hosted fields component

- e2e-tests/bundle/bundle-size.test.js
- rollup.config.js
The legacy paypal-js library, which supposedly should work on IE11, does not compile to ES5.
This overrides the `target: "esnext"` in `tsconfig.json`
> fix: override tsconfig target in legacy build

- types/components/buttons.d.ts
- The current links on `createOrder` , `createSubscription` and `onApprove` methods reference on [React PayPal JS StoryBook documentation](https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--default) points to the [API Reference page](https://developer.paypal.com/docs/api/orders/v2/), however, such resource does not provide enough information about how to use the mentioned methods, but how they work internally. That's why this PR updates such links to point at the [JavaScript SDK references](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-reference) which has more complete information about how to use them properly and how to handle their params.
> improve buttons params documentation

- types/components/hosted-fields.d.ts
- types/index.d.test.ts
The HostedFields.createOrder function is required and doesn't received any arguments from the callback. 
The user needs to handle the order creation process manually.
In this PR we fix those issues.
> Fix problem in HostedFields.createOrder argument types

- types/components/hosted-fields.d.ts
The hosted-fields.d.ts declare a HostedFieldsHandler.submit function returning a Promise<void>.
In this PR we fix the return type, because the submit return an object containing valuable information to use after the payment was validated.
> Support return type on hostedFields submit method

- README.md
updated README to include Async/Await examples. I left the original examples and labelled them as Promises. Open to removing them, changing the labels, or anything else.
> docs: update docs to use async/await syntax

- README.md
I was dreaming about JS error handling and realized we should recommend a separate error handler for `render()` calls since that also returns a promise. 
Here's the reference to the zoid types for `render()` and `renderTo()` which we use in the sdk: https://github.com/krakenjs/zoid/blob/master/src/component/component.js#L138-L139. The render returns a Promise because it needs to get acknowledgement from the iframe window within a certain time period.
> docs: separate out catch for render() errors

- .eslintrc.json
- src/load-script.test.ts
- src/load-script.ts
- src/utils.ts
**Current problem**: 
The final client/user cannot see the real problem message problem when are getting the SDK library. We're returning all the time the same message:  `The script "${url}" failed to load.`. The `url` represents the sandbox/PayPal server from where we load the SDK.
Nevertheless, we receive the real problem message in the server response as a string and we never use that message to report him the real source of the problem.
This is a server response example:
```
throw new Error("SDK Validation error: 'Expected client-id to be passed'");
/* Original Error:
Expected client-id to be passed (debug id: f124435555fb3)
*/
```
**Proposal**:
The idea is to get the error response from the server, parse it and return it. In the `onError` callback of the `insertScriptElement` …
> Enhance 400 error messages

- e2e-tests/bundle/bundle-size.test.js
- src/utils.ts
When testing in IE 11 I noticed that `Object.assign()` errors out and we don't polyfill it. I refactored the code to avoid using Object.assign()`.
> fix(ie11): remove usage on Object.assign

- src/load-script.test.ts
This PR cover missing lines in the test cases on the file load-script.test.ts. We missing a specific case when the script fails to load but trying to get the server error response the script is loaded.
The main reason for this change is to avoid uncovered lines in the new functionality related to getting the server error messages.
Previous test cases show this: 
After the change we have this result:
> Increase test coverage

- types/components/hosted-fields.d.ts
We have an unneeded type definition in the file `types/components/hosted-fields.d.ts`.
This PR removed that unused type from the hosted-fields type script definition
> Remove unused create order type

- types/apis/orders.d.ts
Get rid of the deprecated type`CaptureOrderResponseBody` in orders.d.ts
We don;t need anymore the type `CaptureOrderResponseBody` on the repo.
> Remove deprecated order type

- types/apis/subscriptions/subscriptions.d.ts
- types/components/buttons.d.ts
- types/components/hosted-fields.d.ts
- types/index.d.ts
The PR contains all re-exported module types to avoid importing types from different directories inside the library.
Final users can `import type { * } from "@paypal/paypal-js"` directly. 
The main reason is to make the developers live a little easier using our libraries.
Maybe it can be useful as well start documenting all the types to avoid confusion or research on the web to understand the defined types for the library.
This PR depends on the changes/enhancements made on [Enhance the missing subscription type on OnApproveAction callback](https://github.com/paypal/paypal-js/pull/140)
> Export all modules types from the main file index.d.ts

- types/index.d.ts
The PR contains the reexport `PayPalScriptOptions` type from the `index.d.ts` file
This change avoids importing the `PayPalScriptOptions` from the relative file path.
> Reexport missing PayPalScriptOptions type

- package-lock.json
- package.json
- scripts/check-node-version.js
This PR removes the `check-node-version` dependency and uses `semver` to validate the Node version instead. My thought process here was to reduce dev dependencies. It still uses `chalk` for the nicely formatted output.
The new output is not identical. This PR doesn't include the printed range since I couldn't figure out how to do that with `semver` but I'm hoping people can just infer that from the expected version defined in .npmrc.
Old output for version mismatch:
New output for version mismatch:
> chore: use semver for node version check

- types/components/messages.d.ts
See #165 
The props of style in interface `PayPalMessagesComponentOptions` is missing.
Update type [message.d.ts](https://github.com/paypal/paypal-js/blob/main/types/components/messages.d.ts) by following the properties from [Customize Pay Later messages](https://developer.paypal.com/docs/checkout/pay-later/us/integrate/customize-messages/) .
**What kind of change does this PR introduce?**
type declaration fix
**Does this PR introduce a breaking change?**
No
> fix(types): add missing style props

- types/components/hosted-fields.d.ts
The PR contains missing types from `PayPalHostedFieldsComponentOptions`  to enhance the `installments` missing option type for hosted fields.
To enhance the hosted fields types and make visible the `installments` option in the render function to developers integrating our SPB in their merchant clients.
> chore(types): enhance hosted fields types

- types/apis/orders.d.ts
- types/tests/buttons.test.ts
This PR is a follow up to https://github.com/paypal/paypal-js/pull/268 and includes the following changes:
- Update shipping name, address, phone_number, and email to be optional (https://developer.paypal.com/docs/api/orders/v2/#definition-shipping_detail)
- Update shipping types to enforce the rule of having either` shipping.type` or `'shipping.options` but not both. This enforces the following requirement from the rest api docs:
> The method by which the payer wants to get their items from the payee e.g shipping, in-person pickup. Either type or options but not both may be present.
> fix(types): update order shipping options to match spec

- types/components/hosted-fields.d.ts
- types/tests/hosted-fields.test.ts
This PR improves the types for Hosted Fields by adding support for `hostedFieldsInstance.on()` and `hostedFieldsInstance.off()`.
Resolves #298
> fix(types): add missing on and off events for hostedFields

- types/apis/subscriptions/subscriptions.d.ts
- types/components/buttons.d.ts
Improve the types for the Subscription flow. This PR adds types for the `actions.subscription.revise()` function.
Resolves: https://github.com/paypal/react-paypal-js/issues/312
> fix(types): add missing action for revising a subscription

- src/load-script.ts
Updated environment checks to check for `document` rather than `window` to make code Deno-safe, as Deno has a [window](https://deno.land/api@v1.28.3?s=Window) object.
> fix: update load-script.js

- types/components/buttons.d.ts
https://paypal.atlassian.net/browse/DTPPSDK-1109
patch order returns 204 no content, so OnShippingChangeActions patch should return `Promise<void>`
> fix(types): update patch order response

- types/apis/orders.d.ts
- types/components/buttons.d.ts
Updates the "patch" function for button callbacks to be consistent with the documented behavior for v2 of the PayPal orders API.
Reference:
- https://developer.paypal.com/docs/api/orders/v2/#orders_patch
- https://developer.paypal.com/docs/checkout/advanced/customize/update-order-details/#link-updateorderdetails
> fix(types): update patch request body for order actions

- types/apis/orders.d.ts
- types/tests/server.test.ts
This PR adds a test to validate the new types added in #360 for the [Update Order patch operation](https://developer.paypal.com/docs/api/orders/v2/#orders_patch).
It also removes the "move" operation from the patch api call types. Based on [this list](https://developer.paypal.com/docs/api/orders/v2/#orders_patch), no attributes actually support the "move" operation.
> chore(types): add test for patching order

- README.md
- e2e-tests/browser-global.html
- e2e-tests/load-cached-script.html
- e2e-tests/reload-script.html
- e2e-tests/validation-errors.html
- src/load-script.node.test.ts
- src/load-script.test.ts
- src/utils.test.ts
- src/utils.ts
- types/script-options.d.ts
- types/tests/buttons.test.ts
- types/tests/hosted-fields.test.ts
- types/tests/load-script.test.ts
This PR makes a breaking interface change for the types for the `loadScript(PayPalScriptOptions)` loader function. It changes the `PayPalScriptOptions` interface to use camelCase instead of kebab-case.
I think this would improve the developer experience since JS devs are familiar to camelCase for all the things. Note that we would still pass query params and data attributes as kebab-case under the hood but would hide this from the public interface.
The TypeScript types have been updated to use camelCase format for `PayPalScriptOptions` and follow this Google JS Style Guide for naming conventions for acronyms.
https://google.github.io/styleguide/jsguide.html#naming-camel-case-defined
```js
loadScript({ 
"client-id": "test", 
"merchant-id": ["123", "456", "789"] 
});
```
```js
loadScript({ …
```
> Use camelCase instead of kebab-case for params (breaking change!)

- .eslintrc.json
- bundle-tests/bundle-size.test.js
- bundle-tests/es3.test.js
- jest.config.js
- package-lock.json
- package.json
- src/load-script.node.test.ts
- src/load-script.test.ts
- src/load-script.ts
- src/utils.test.ts
- vitest.config.ts
This PR replaces Jest with [vitest](https://vitest.dev/).
I stuck with jsdom since happy-dom executes `<script>` tags by default and was difficult to switch out. There are also some differences in type definitions for the DOM. Sticking with jsdom made this upgrade pretty easy.
> chore(tests): use vitest

- types/script-options.d.ts
The `disableFunding` param is the recommended way to prevent specific funding instruments from showing in the smart buttons stack. To disable the card, `disableFunding: "card"` should be used instead of the legacy `disableCard` option.
> fix(types): remove deprecated disableCard param

- types/apis/orders.d.ts
- types/tests/server.test.ts
The [payment_source](https://developer.paypal.com/docs/api/orders/v2/#orders_create!path=payment_source&t=request) option is for defining configuration for specific funding sources when creating an order. This PR adds types for this new option. Right now, it only types the `paypal` option. Other options will be added in future PRs.
Example usage: https://github.com/gregjopa/paypal-button-full-page-redirect-example/blob/main/src/controllers/order-controller.ts#L76
> fix(types): add types for payment_source with order creation

- README.md
- src/utils.test.ts
- types/script-options.d.ts
Follow up to #419. Applies the same array or string type logic to `components` and also fixes the types for `disableFunding` and `integrationDate`.
cc: @CBoensel
> fix(types): query params as an array or string

- types/components/buttons.d.ts
`disableMaxWidth` was missing. 
See https://developer.paypal.com/sdk/js/reference/#link-width
> Add new param to style type def

- types/components/buttons.d.ts
This PR adds type definitions for two new callbacks that were implemented in https://github.com/paypal/paypal-smart-payment-buttons/pull/679
Also see the react-paypal-js changes, which consume these changes here: https://github.com/paypal/react-paypal-js/pull/388
> feat: add type definitions for two new callbacks

- types/components/buttons.d.ts
Adding the new `displayOnly` config option which will allow merchants to show only vaultable buttons.
```
paypal.Buttons({
displayOnly: ["vaultable"]
})
```
> Add displayOnly config option

- src/load-script.ts
- src/utils.test.ts
- src/utils.ts
- types/script-options.d.ts
This PR adds support for the [crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) script attribute. 
For example, the following `loadScript()` call will create the following script tag in the DOM:
```js
loadScript({ clientId: "test", crossorigin: "anonymous" })
```
```html
<script src="https://www.paypal.com/sdk/js?client-id=test" crossorigin="anonymous"></script>
```
Resolves #434
> feat: add support for crossorigin script attribute

- types/components/buttons.d.ts
Adding support for the `createVaultSetupToken` callback to our type definitions. Documented [here](https://developer.paypal.com/docs/checkout/save-payment-methods/purchase-later/js-sdk/paypal/#link-clientsidecodesample)
> fix: add type definitions for createVaultSetupToken

- package.json
This PR updates the code coverage report to only include the files in the src folder. Previously the `e2e-tests` and `scripts` folders were getting included by accident.
> chore: update code coverage to only include src folder

- .changeset/sweet-ants-fix.md
- packages/paypal-js/types/script-options.d.ts
This PR will resolve the following type error in `react-paypal-js` when adding `dataJsSdkLibrary` to `loadScript()`:
> Add dataJsSdkLibrary to PayPalScriptDataAttributes

- .changeset/catfish-papaya.md
- packages/paypal-js/types/index.d.ts
Export card fields types from index
> chore: export card fields types from index

- .changeset/olive-plums-begin.md
- packages/paypal-js/types/components/buttons.d.ts
- packages/paypal-js/types/components/card-fields.d.ts
**JIRA:** [LI-40638](https://paypal.atlassian.net/browse/LI-40638)
This will help us align with the types in our docs 😄 
I didn't realize this repo auto-formats when you commit. So here's the lines I actually changed:
- [Made facilitatorAccessToken optional in onApproveData](https://github.com/paypal/paypal-js/pull/475/files#diff-66eb7d7ed93786f74449389e63635c5bddcd2d12912a143640e96416e3498a51R49)
- [Changed onApprove param from err to data with onApproveData as the type](https://github.com/paypal/paypal-js/pull/475/files#diff-3cd5a8f75e518348830337978d300aa8b7c7f29407d2b1cd629aaa4fc1b30a46R129)
> Update onApprove Param Type 👾

- .changeset/eminent-choufer.md
- packages/paypal-js/types/components/card-fields.d.ts
Some of the types in cardfields are not accurate. more work needs to be done to include the correct types and props for each cardfield. This PR aims to correct some of the types that are already there.
> fix: adjust current type props

- .changeset/good-falcons-turn.md
- .gitignore
- packages/paypal-js/src/load-script.test.ts
- packages/paypal-js/src/load-script.ts
- packages/paypal-js/src/utils.ts
- packages/paypal-js/types/components/card-fields.d.ts
- packages/paypal-js/types/index.d.ts
- packages/paypal-js/types/script-options.d.ts
* Introduce a new option in the `loadScript` method to allow passing `env = sandbox or production`.
*  If `env=sandbox` is passed as an option, then the sdk script will be loaded from `www.sandbox.paypal.com/sdk/js`
> Introduce env parameter to support sandbox and paypal 

- .changeset/fluffy-tigers-mate.md
- packages/react-paypal-js/src/components/PayPalButtons.tsx
Button rerender was rerendering unintentionally due to a non-primitive value, the message obj, being passed into the useEffect dependency array.  This fixes the issue by stringify-ing the message.
> fix: button rerender issue due to obj in dependency array

- .changeset/small-cups-buy.md
- packages/paypal-js/types/components/buttons.d.ts
Using the latest v8.5.0 version of the `@paypal/react-paypal-js` package, the `style` object for `<PayPalButtons>` doesn’t include a typed field for the `borderRadius` option listed in the button’s [SDK documentation](https://developer.paypal.com/sdk/js/reference/#link-borderradius).
This PR adds `PayPalButtonsComponentOptions.style.borderRadius` with the documented `number` type.
> Add missing button border radius type

- .changeset/cold-mangos-sleep.md
- packages/paypal-js/types/components/buttons.d.ts
- packages/react-paypal-js/src/components/PayPalButtons.test.tsx
- packages/react-paypal-js/src/components/PayPalButtons.tsx
There was a bug where updating button message properties such as `amount` would tear down then rebuild the entire button component to render the new message.  This fix allows just the message to rerender and preserves the button.
**Testing instructions:** 
_Setup_
- open this `paypal-js` PR locally
- execute `npm run build` in paypal-js
- open `paypal-js` file explorer to `packages/react-paypal-js/dist` and copy the `cjs` and `esm` directories
- open [this lighthouse-ecommerce AKA "Palmart" PR](https://github.paypal.com/credit-merchant/lighthouse-ecommerce/pull/4) locally
- run `npm install`
- open Palmart file explorer to `node_modules/@paypal/react-paypal-js/dist`
- delete the `cjs` and `esm` directories
- paste copied `cjs` and `esm` directories there
- delete `.next` directory …
> fix: message props update without button teardown

- .changeset/thirty-impalas-relate.md
- packages/paypal-js/types/components/buttons.d.ts
- packages/react-paypal-js/src/stories/components/CopyButton.tsx
Split up each prop in  into its own type to export
// Old way
const styles: PayPalButtonsComponentOptions["styles"] = { ...your_button_styles }
// New way
const styles: PayPalButtonsStyles = { ...your_button_styles }
> Export type for buttons components props

- .changeset/wild-turtles-remain.md
- packages/paypal-js/src/utils.test.ts
- packages/paypal-js/src/utils.ts
Removed `delete` statements from `processOptions` function to prevent modifying its argument and having side-effects.
Deleting `sdkBaseUrl` property is causing to React script loader to not properly set a custom `sdkBaseUrl` because `useEffect` is running twice.
> Refactor `processOptions` to prevent modifying its arguments

- .changeset/modern-drinks-think.md
- .changeset/silly-bears-boil.md
- packages/paypal-js/types/components/card-fields.d.ts
- packages/paypal-js/types/tests/card-fields.test.ts
This pr is to fix this [LI-73058](https://paypal.atlassian.net/browse/LI-73058)
Problem: the createOrder callback is require when createVaultToken is implement when it should be one or the other and not both. 
Closes #587
Closes #580
> create new types for createOrder and creatVaultToken

- packages/paypal-js/package.json
- packages/react-paypal-js/package.json
Two small changes:
- The `repository.url` of `react-paypal-js` was still pointing to the old repository. That URL is used for the "Homepage" link on npm. 
- Added `repository.directory` to point to the correct folder within this repository
> chore: update `repository` field in `package.json` files

- .changeset/mean-chefs-love.md
- packages/paypal-js/types/components/buttons.d.ts
Extends `PayPalButtonsComponent` and `PayPalButtonsComponentOptions` to include direct app switch props and methods.
> (chore) add types for PPCP v5 App Switch

- .changeset/curly-otters-clean.md
- packages/react-paypal-js/src/types/payPalCardFieldsTypes.ts
Implement a fix for issue https://github.com/paypal/paypal-js/issues/624
Now the types are matching the docs entirely: https://developer.paypal.com/docs/checkout/advanced/customize/card-field-style/
There is a similar PR already approved (solves a few, but not for all styles): https://github.com/paypal/paypal-js/pull/616
For the MozAppearance, there was a typo error
> fix style fields to CardField Types

- .changeset/twenty-emus-build.md
- packages/paypal-js/src/v6/index.test.ts
- packages/paypal-js/src/v6/index.ts
This PR adds the `loadCoreSdkScript()` script loader function for v6. Ex:
```ts
import {
loadCoreSdkScript
} from "@paypal/paypal-js/sdk-v6";
const paypalNamespaceReference = await loadCoreSdkScript({ environment: "sandbox", debug: true });
const sdkInstance = await paypalNamespaceReference.createInstance({ 
clientToken, 
components: ["paypal-payments"] 
});
```
The `loadCustomScript()` function was removed and replaced with this new `loadCoreSdkScript()` function for improved readability.
> feat: Add `loadCoreSdkScript` script loader for v6 sdk
