paypal/paypal-js

README.md, package.json
This PR documents the browser support and also adds a some [keywords for npm](https://docs.npmjs.com/files/package.json#keywords).
=> Document Browser support and add keywords

.npmrc, README.md, package-lock.json, package.json, scripts/publish.js, scripts/validate.js
This PR creates a couple helper scripts for publishing a new release to npm. It also documents the release process.
=> Document release process

README.md, package.json
Folks have been asking questions like "What are the advantages of using paypal-js?". This PR adds a section to the readme to explain the benefits.
=> Add section explaining why folks should use paypal-js

README.md
Use new developer.paypal.com link for browser support info.
=> Update link to docs page about browser support

.github/workflows/main.yml, .travis.yml, README.md
=> Added GitHub Actions for CI and updated README

types/apis/orders.d.ts, types/components/buttons.d.ts
Adds a type for using `actions.order.authorize()` in `onApprove`.
=> fix(types): add type for authorize()

types/components/buttons.d.ts, types/index.d.test.ts
This PR fixes an issue with the types for the onApprove actions. Resolves #112.
=> fix(types): move restart() and redirect() onApprove actions

tsconfig.json, types/index.d.test.ts
The PR has two main changes.
- The first one update the `tsconfig` file to include the `types` folder and change the `rootDir` path.
- The second change is to fix all the issues related to types on the `index.d.test.ts` file and pass the `typecheck` successfully.
The typescript wasn't able to inspect/compile the `index.d.test.ts` due to the current `tsconfig`. The typescript compiler wasn't able to notify errors about the use of the newly defined types and wasn't working properly.
Take a look at how the test file guides the typescript compiler about possible `undefined` objects. Any comments/suggestion/improve is welcome.
=> Include typescript compiler on types test files

types/apis/orders.d.ts, types/components/buttons.d.ts, types/tests/buttons.test.ts
The PR contains the needed fixes exposed in this [issue](https://github.com/paypal/paypal-js/issues/216). 
To continue improving our types and make it easier for the life of external developers.
They're missing types we'll continue improving in the future.
Closes #216
=> Fixes related to issue 216

types/components/messages.d.ts
I have added the missing options and removed account since it is not listed in the docs.
https://github.com/paypal/paypal-js/issues/269
=> Update messages type to match current documentation

README.md
=> docs(readme): add example for "components" query string param

types/apis/orders.d.ts
=> fix(types): add type for minimal response from orders api

types/script-options.d.ts
See issue description of #418 and commit messages below. 
Hope that works. 
@gregjopa Let me know if anything else is needed from my end. Thanks.
=> Minor type defintion changes for script loading options

types/components/card-fields.d.ts, types/index.d.ts
=> feat: add types for card fields

.changeset/smart-foxes-trade.md, packages/paypal-js/types/components/buttons.d.ts
Update PayPalButtonsComponentOptions to add message
=> Update PayPalButtonsComponentOptions to add message

README.md
=> update readme to include react package

.changeset/fluffy-tigers-mate.md, .changeset/rare-geckos-shake.md, package-lock.json, packages/react-paypal-js/CHANGELOG.md, packages/react-paypal-js/package.json
=> Revert "Version Packages"

.changeset/curly-monkeys-itch.md, packages/paypal-js/types/components/buttons.d.ts
Added shape: "sharp" 
borderRadius: number was already added
Ticket: https://paypal.atlassian.net/browse/DTPPCPSDK-2114
=> add shape: sharp

.changeset/grumpy-tigers-build.md, .github/workflows/playwright.yml, packages/react-paypal-js/package.json, packages/react-paypal-js/tsconfig.declarations.json, scripts/check-node-version.js
=> fix release job, add react 19 as peer dependency

.changeset/little-suits-camp.md, packages/react-paypal-js/src/types/payPalCardFieldsTypes.ts
added missing style fields to CardField Types
=> added missing style fields to CardField Types

.changeset/proud-tigers-report.md, packages/paypal-js/types/v6/components/base-component.d.ts, packages/paypal-js/types/v6/components/paypal-legacy-billing-agreements.d.ts, packages/paypal-js/types/v6/components/paypal-payments.d.ts, packages/paypal-js/types/v6/components/venmo-payments.d.ts, packages/paypal-js/types/v6/index.d.ts, packages/paypal-js/types/v6/tests/paypal-legacy-billing-agreements.test.ts, packages/paypal-js/types/v6/tests/paypal-payments.test.ts, packages/paypal-js/types/v6/tests/venmo-payments.test.ts
This PR updates the v6 TypeScript types
=> feat(types): improve v6 types and add tests
